### ISSUE TITLE
initial pass at fixing credits - suggestions welcome

### ISSUE THREAD

**Issue by eschipul** [goetzk/tendenci-community#4]
Karl - just seeing this now. No excuse besides being overwhelmed. However I take your advice very seriously and made some updates to the credits file this evening and committed them to master. I realize there is a lot of work to be done, but hopefully this corrects the most glaring omission. 

https://github.com/tendenci/tendenci/blob/master/docs/credits.md

.... I realize I have not addressed everything in the doc, and maybe that's a skype call? Thank you, and first steps taken....  I'm @eschipul on skype and most social media.

**Comment by goetzk** [comment]
Hi @eschipul ,
Appologies from my side too - I was hoping to spend a month or two working on this document then sharing it (so it wasn't discovered, rather delivered). I too wound up swamped.

Thanks for taking the concerns seriously and I'm happy to talk about them more - I sent you a message on skype (since I don't have social media), you may see it next time you log in.

I suspect communication will only be burts of text for a month or two to come, but happy to see a message there or an email if you ever wish.

Karl.

**Comment by goetzk** [comment]
Docs have moved since we had this conversation
https://github.com/tendenci/tendenci/blob/master/docs/source/credits/credits.txt
https://tendenci.readthedocs.io/en/latest/credits/credits.html

Thanks for taking this issue seriously and for the updates you made to the projects credits!

(still happy to call some time if you'd like; ping me if you would).
